.

diff --git a/gitfetch b/gitfetch
--- a/gitfetch
+++ b/gitfetch
@@ -4,33 +4,28 @@ set -x #print commands
 
 . ~/scripts/git-utils
 
-# UPDATED=no
+UPDATED=no
 
 # # just drop changes to this file because it is useless and always getting auto-updated
 # [[ -f package-lock.json ]] && git restore package-lock.json
 
-# set -e #exit on failed command
+set -e #exit on failed command
 
-# stash_before gitfetch-tmp
-
+stash_before gitfetch-tmp
 
 echo "fetch origin $MAIN && git rebase origin/$MAIN"
-set +u
-if git fetch origin "$MAIN" && git rebase "origin/$MAIN"; then
 
-  # was HEAD updated?
-  if [[ "$(git rev-parse HEAD)" != "$(git rev-parse HEAD@{1})" ]]; then
-    UPDATED=yes
-  fi
+if git fetch origin "$MAIN" && git rebase "origin/$MAIN"; then
+  :
+#  # was HEAD updated?
+#  if [[ "$(git rev-parse HEAD)" != "$(git rev-parse HEAD@{1})" ]]; then
+#    UPDATED=yes
+#  fi
 else
   rich "[bold red]Failed to fetch and rebase[/bold red]" --print
 fi
-set -u
 
-# # Reset -u
-# set -u
-
-# pop_after || (rich "[bold red]FAILED TO POP STASH![/bold red]" --print && exit 1)
+pop_after || (rich "[bold red]FAILED TO POP STASH![/bold red]" --print && exit 1)
 
 
 # if [[ $UPDATED != yes ]]; then
